### ISSUE TITLE
Error: Missing argument path

### ISSUE THREAD

**Issue by SentientCrab** [beakerbrowser/dat-node#8]
Using Centos 7, node version 10.9.0 and I'm getting the following error that I can't figure out. This is my first time using node so this may be very simple, but whenever I run any of the examples I get this error:
```/root/node_modules/@beaker/dat-node/lib/util.js:94
    throw new BadArgumentError(`Missing argument ${param}`)
    ^

Error: Missing argument path
    at exports.hasParam (/root/node_modules/@beaker/dat-node/lib/util.js:94:11)
    at new DatNodeStorage (/root/node_modules/@beaker/dat-node/lib/dat-node-storage.js:24:5)
    at new DatNode (/root/node_modules/@beaker/dat-node/lib/dat-node.js:20:20)
    at exports.createNode (/root/node_modules/@beaker/dat-node/lib/dat-node.js:13:10)
    at Object.<anonymous> (/root/node_modules/@beaker/dat-node/examples/simplest-possible-example.js:4:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```
This is from a fresh install of nodejs, instaling dat-node from github, and running `node examples/simplest-possible-example.js`

**Comment by pfrazee** [comment]
Huh, okay let's see... ah. The examples didn't get updated when some params changed. Will push a fix momentarily.

**Comment by pfrazee** [comment]
Okay fixes pushed, lmk if you have any more trouble
